import pytest


class TestException:
    @pytest.mark.skip
    def test_consume_exception(self):
        pass

    @pytest.mark.skip
    def test_produce_exception(self):
        pass
